version: '3'
services: 
  db:
    image: mariadb:latest
    volumes:
      -  ./dbdata:/var/lib/mysql
    ports:
        - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "hoge"
volumes:
  db_data:

